server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/postgres_database
    username: username
    password: password

logging:
  level:
    web: debug
    kafka: debug