eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port:
    8080

my:
  security:
    secret-string: "mySecretStringForKeymySecretStringForKeymySecretStringForKey"