eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  application:
    name: presence-service
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092

server:
  port:
    8093

my:
  security:
    jwt-timeout-in-minutes: 60