eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  application:
    name: presence-service
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: message-handlers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default: java.lang.String
            trusted:
              packages: '*' # Разрешить десериализацию всех пакетов
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
    time-zone: UTC

server:
  port:
    8093

my:
  security:
    jwt-timeout-in-minutes: 60