eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  application:
    name: presence-service
  data:
    redis:
      host: presence-redis
      port: 6381
  kafka:
    bootstrap-servers: kafka:9092

server:
  port:
    8093