server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/postgres_database
    username: username
    password: password
  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
    web: debug
    kafka: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # ← Без пробелов после запятых!
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true