eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  application:
    name: websocket-service
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

server:
  port:
    8092

my:
  security:
    jwt-timeout-in-minutes: 60

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # ← Без пробелов после запятых!
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true