groups:
  - name: gateway-alerts
    rules:
      - alert: GatewayDown
        expr: up{job="gateway"} == 0
        for: 1m  # Минимальное время, чтобы избежать ложных срабатываний
        labels:
          severity: critical
        annotations:
          summary: "Сервис {{ $labels.instance }} недоступен!"
          description: "Сервис {{ $labels.job }} на {{ $labels.instance }} не отвечает более 1 минуты."