spring:
  application:
    name: user-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://config-service:8000
      fail-fast: true
      allow-override: true
  config:
    import: configserver:http://config-service:8000
management:
  endpoints:
    web:
      exposure:
        include: refresh