spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/UserServiceMainDatabase
    username: postgres
    password: 24062005
server:
  port: 8080
logging:
  level:
    web: debug
    kafka: debug